name = "VisualizationBag"
uuid = "2033bc0d-f107-4f18-8621-02511e8703c9"
authors = ["Roy Chih Chung Wang"]
version = "0.1.1"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
